### ISSUE TITLE
谢谢。看kuptun那边刚好看到你已经编译了

### ISSUE THREAD

**Issue by hdstar2009** [bettermanbao/openwrt-kcptun#1]
同题。
现在pc性能不行，cpu都是不用风扇的j1900，编译估计会崩溃。

**Comment by allenkey666** [comment]
这个版本略新一些

**Comment by JogFeelingVI** [comment]
(｡･∀･)ﾉﾞ嗨 哥们儿~，能否请你编译一下 最新版本的kcptun for AR7xxx 版本，觉得不错~ 但是最新版的kcptun 已经出来了，并且增加了压缩代码，与老板本的客户端不兼容，自己又不会编译，所以麻烦一下你，再编译一下新版本 谢谢大神~
