### ISSUE TITLE
极1S下使用效果很差

### ISSUE THREAD

**Issue by ghost** [bettermanbao/openwrt-kcptun#12]
感谢你更新为新版。
使用你编译的版本，新版和旧的20160811版均在极1S路由下表现欠佳，YT上视频经常卡死，路由上KCP进程时常被杀。
而使用[shutup](https://github.com/shutup/kcptun_mip32le/releases)的编译，效果则要好得多，不明原因。
希望能继续优化。

**Comment by ljyloo** [comment]
是不是你的rcvwnd和sndwnd设置得太大了啊

**Comment by allenkey666** [comment]
试试最新版吧，mt7620 64M配置下youtube可以流畅播放1080p, rcvwnd和sndwnd我设置的都是256。

**Comment by ljyloo** [comment]
我测试发现128是个Magic Number，其他数字的ping延迟都会很大，但是到了128就会得到最小值

**Comment by FengkuiChan** [comment]
请问极路由1s如何部署？
