### ISSUE TITLE
还请在首页提供教程

### ISSUE THREAD

**Issue by tianlichunhong** [bettermanbao/openwrt-kcptun#15]
如编译教程
$ cd sdk
$ git clone https://github.com/bettermanbao/openwrt-kcptun.git package/kcptun
$ make package/kcptun/compile V=s
$ find bin -name 'kcptun*.ipk'
还有配置教程。在/etc/config/kcptun中配置？
只是举例，还请详细，谢谢！

**Comment by allenkey666** [comment]
首页提供了luci的安装包，不想打命令的童鞋可以用luci界面配置。
