### ISSUE TITLE
请教个问题，你编译出来的mips kcptun 为什么这么小。。

### ISSUE THREAD

**Issue by rawrence** [bettermanbao/openwrt-kcptun#17]
我加了ldflags参数 -s -w ，大约要3m 左右。你编译出来的mips kcptun 为什么这么小。。
求解

**Comment by allenkey666** [comment]
因为我用UPX压缩了一下，原作者编译完也是用UPX压缩后，再打包发布的。

**Comment by niuniudada** [comment]
运行不了。
![image](https://cloud.githubusercontent.com/assets/12442026/20514336/44b78736-b0c6-11e6-8f71-485685c197fa.png)

**Comment by vmtime** [comment]
路由器上使用要关闭压缩功能, 修改下 config.json 里面的: nocomp 配置为 true
参考之前的问题 #5

**Comment by allenkey666** [comment]
server和client的config文件建议参考我提供的样本。
电信宽带下可以做到youtube视频1080p流畅播放，又不至于太快导致路由器负载过高。

**Comment by niuniudada** [comment]
@xtime2100 @bettermanbao 已经可以了，谢谢，可惜网速没办法达到1080P。

**Comment by allenkey666** [comment]
用了我推荐的配置文件了吗？

**Comment by rawrence** [comment]
谢谢 @bettermanbao

**Comment by haruhitamako** [comment]
@bettermanbao 原作者的版本有3m大，B大你的只有1.5m。8m闪存用原作者的压力山大。而且原版的目前无法在原版openwrt使用。希望以后原作者有大改版能更新一下你的版本给小内存用。

**Comment by allenkey666** [comment]
已经联系原作者，今后会启用压缩。
