### ISSUE TITLE
最新的1118版本，netgear 3700v4 报错

### ISSUE THREAD

**Issue by tisswb** [bettermanbao/openwrt-kcptun#18]
通过/usr/bin/kcptun/client -c /var/etc/kcptun/client.json命令启动ar71xx这个后，只要一连接，就会报下面的错误

`
panic: runtime error: slice bounds out of range

goroutine 18 [running]:
github.com/klauspost/compress/snappy.encodeBlock(0x105d0013, 0x12ac9, 0x12ac9, 0x1059a000, 0x1a, 0x10000, 0xb900f380)
	/opt/mipsgo/src/github.com/klauspost/compress/snappy/encode_other.go:175 +0x10c4
github.com/klauspost/compress/snappy.Encode(0x105d0012, 0x12aca, 0x12aca, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/klauspost/compress/snappy/encode.go:37 +0x370
github.com/klauspost/compress/snappy.(*Writer).write(0x1053c7e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/klauspost/compress/snappy/encode.go:229 +0x280
github.com/klauspost/compress/snappy.(*Writer).Flush(0x1053c7e0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/klauspost/compress/snappy/encode.go:272 +0xb0
main.(*compStream).Write(0x105387d0, 0x10608000, 0x1a, 0x10008, 0x1a, 0x0, 0x0)
	/home/openwrt/kcptun/client/main.go:40 +0x88
github.com/xtaci/smux.(*Session).writeFrame(0x10510190, 0x1020000, 0x3, 0x10634000, 0x12, 0x8000, 0x1050ad20, 0x0, 0x0)
	/opt/mipsgo/src/github.com/xtaci/smux/session.go:271 +0x4b8
github.com/xtaci/smux.(*Stream).Write(0x1053a090, 0x10634000, 0x12, 0x8000, 0x12, 0x0, 0x0)
	/opt/mipsgo/src/github.com/xtaci/smux/stream.go:88 +0x190
io.Copy(0x779ea4c8, 0x1053a090, 0x779ea4e0, 0x1051c2a8, 0x0, 0x3, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:364 +0x288
main.func·002()
	/home/openwrt/kcptun/client/main.go:67 +0xd8
created by main.handleClient
	/home/openwrt/kcptun/client/main.go:67 +0x578

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0x105560b8, 0x72, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:84 +0x4c
net.(*pollDesc).WaitRead(0x105560b8, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:89 +0x48
net.(*netFD).accept(0x10556080, 0x0, 0x779e8b10, 0x105383f0)
	/opt/mipsgo/src/net/fd_unix.go:419 +0x3dc
net.(*TCPListener).AcceptTCP(0x1051c2a0, 0x1051c2b0, 0x0, 0x0)
	/opt/mipsgo/src/net/tcpsock_posix.go:234 +0x58
main.func·005(0x10500aa0, 0x0, 0x0)
	/home/openwrt/kcptun/client/main.go:376 +0x2620
reflect.Value.call(0x223d60, 0x2caf14, 0x13, 0x277e68, 0x4, 0x10529ac0, 0x1, 0x1, 0x0, 0x0, ...)
	/opt/mipsgo/src/reflect/value.go:419 +0xff0
reflect.Value.Call(0x223d60, 0x2caf14, 0x13, 0x10529ac0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/reflect/value.go:296 +0xb0
github.com/urfave/cli.HandleAction(0x223d60, 0x2caf14, 0x10500aa0, 0x0, 0x0)
	/opt/mipsgo/src/github.com/urfave/cli/app.go:487 +0x27c
github.com/urfave/cli.(*App).Run(0x10566000, 0x1050a000, 0x3, 0x3, 0x0, 0x0)
	/opt/mipsgo/src/github.com/urfave/cli/app.go:245 +0x9e0
main.main()
	/home/openwrt/kcptun/client/main.go:406 +0x1418

goroutine 5 [syscall]:
os/signal.loop()
	/opt/mipsgo/src/os/signal/signal_unix.go:21 +0x30
created by os/signal.init·1
	/opt/mipsgo/src/os/signal/signal_unix.go:27 +0x58

goroutine 6 [chan receive]:
main.sigHandler()
	/home/openwrt/kcptun/client/signal.go:23 +0x150
created by main.init·1
	/home/openwrt/kcptun/client/signal.go:15 +0x48

goroutine 7 [select]:
github.com/xtaci/kcp-go.(*UDPSession).updateTask(0x1057e080)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:511 +0x33c
created by github.com/xtaci/kcp-go.newUDPSession
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:120 +0x524

goroutine 8 [select]:
github.com/xtaci/kcp-go.(*UDPSession).outputTask(0x1057e080)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:412 +0x1a60
created by github.com/xtaci/kcp-go.newUDPSession
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:121 +0x554

goroutine 9 [select]:
github.com/xtaci/kcp-go.(*UDPSession).readLoop(0x1057e080)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:629 +0x50c
created by github.com/xtaci/kcp-go.newUDPSession
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:123 +0x594

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0x10561638, 0x72, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:84 +0x4c
net.(*pollDesc).WaitRead(0x10561638, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:89 +0x48
net.(*netFD).readFrom(0x10561600, 0x10580800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x779e8b10, 0x10538570)
	/opt/mipsgo/src/net/fd_unix.go:269 +0x418
net.(*UDPConn).ReadFromUDP(0x1051c378, 0x10580800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/udpsock_posix.go:67 +0x108
net.(*UDPConn).ReadFrom(0x1051c378, 0x10580800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/udpsock_posix.go:82 +0x104
github.com/xtaci/kcp-go.(*UDPSession).receiver(0x1057e080, 0x10560180)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:610 +0x108
created by github.com/xtaci/kcp-go.(*UDPSession).readLoop
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:626 +0x84

goroutine 12 [select]:
github.com/xtaci/kcp-go.(*UDPSession).Read(0x1057e080, 0x105f4000, 0x4, 0x12ace, 0xa, 0x0, 0x0)
	/opt/mipsgo/src/github.com/xtaci/kcp-go/sess.go:184 +0x8d0
io.ReadAtLeast(0x779ea310, 0x1057e080, 0x105f4000, 0x4, 0x12ace, 0x4, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:298 +0x118
io.ReadFull(0x779ea310, 0x1057e080, 0x105f4000, 0x4, 0x12ace, 0x10554800, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:316 +0x6c
github.com/klauspost/compress/snappy.(*Reader).readFull(0x105601c0, 0x105f4000, 0x4, 0x12ace, 0x1000000, 0x1000000)
	/opt/mipsgo/src/github.com/klauspost/compress/snappy/decode.go:108 +0x6c
github.com/klauspost/compress/snappy.(*Reader).Read(0x105601c0, 0x1061a000, 0x8, 0x10008, 0x779ea420, 0x0, 0x0)
	/opt/mipsgo/src/github.com/klauspost/compress/snappy/decode.go:128 +0x1bc
main.(*compStream).Read(0x105387d0, 0x1061a000, 0x8, 0x10008, 0x0, 0x0, 0x0)
	/home/openwrt/kcptun/client/main.go:35 +0x5c
io.ReadAtLeast(0x779ea420, 0x105387d0, 0x1061a000, 0x8, 0x10008, 0x8, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:298 +0x118
io.ReadFull(0x779ea420, 0x105387d0, 0x1061a000, 0x8, 0x10008, 0x2, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:316 +0x6c
github.com/xtaci/smux.(*Session).readFrame(0x10510190, 0x1061a000, 0x10008, 0x10008, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/mipsgo/src/github.com/xtaci/smux/session.go:162 +0x104
github.com/xtaci/smux.(*Session).recvLoop(0x10510190)
	/opt/mipsgo/src/github.com/xtaci/smux/session.go:197 +0x1d8
created by github.com/xtaci/smux.newSession
	/opt/mipsgo/src/github.com/xtaci/smux/session.go:62 +0x358

goroutine 13 [select]:
github.com/xtaci/smux.(*Session).keepalive(0x10510190)
	/opt/mipsgo/src/github.com/xtaci/smux/session.go:245 +0x360
created by github.com/xtaci/smux.newSession
	/opt/mipsgo/src/github.com/xtaci/smux/session.go:63 +0x384

goroutine 14 [select]:
main.scavenger(0x10560280)
	/home/openwrt/kcptun/client/main.go:423 +0x648
created by main.func·005
	/home/openwrt/kcptun/client/main.go:373 +0x2608

goroutine 15 [select]:
main.handleClient(0x779ea3e0, 0x1051c2a8, 0x779ea400, 0x1053a090)
	/home/openwrt/kcptun/client/main.go:70 +0x65c
created by main.func·005
	/home/openwrt/kcptun/client/main.go:402 +0x30ec

goroutine 16 [select]:
main.handleClient(0x779ea3e0, 0x1051c2b0, 0x779ea400, 0x1053a120)
	/home/openwrt/kcptun/client/main.go:70 +0x65c
created by main.func·005
	/home/openwrt/kcptun/client/main.go:402 +0x30ec

goroutine 17 [select]:
github.com/xtaci/smux.(*Stream).Read(0x1053a090, 0x1062c000, 0x8000, 0x8000, 0x0, 0x779e49c0, 0x1051c068)
	/opt/mipsgo/src/github.com/xtaci/smux/stream.go:68 +0x6a8
io.Copy(0x779ea498, 0x1051c368, 0x779ea450, 0x1053a090, 0x0, 0x2, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:362 +0x208
net.genericReadFrom(0x779ea438, 0x1051c2a8, 0x779ea450, 0x1053a090, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/net.go:404 +0xb4
net.(*TCPConn).ReadFrom(0x1051c2a8, 0x779ea450, 0x1053a090, 0x779ea480, 0x1051c2a8, 0x0, 0x0)
	/opt/mipsgo/src/net/tcpsock_posix.go:72 +0x118
io.Copy(0x779ea438, 0x1051c2a8, 0x779ea450, 0x1053a090, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:358 +0x154
main.func·001()
	/home/openwrt/kcptun/client/main.go:64 +0xd8
created by main.handleClient
	/home/openwrt/kcptun/client/main.go:64 +0x448

goroutine 19 [select]:
github.com/xtaci/smux.(*Stream).Read(0x1053a120, 0x10644000, 0x8000, 0x8000, 0x0, 0x779e49c0, 0x1051c068)
	/opt/mipsgo/src/github.com/xtaci/smux/stream.go:68 +0x6a8
io.Copy(0x779ea498, 0x1051c810, 0x779ea450, 0x1053a120, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:362 +0x208
net.genericReadFrom(0x779ea438, 0x1051c2b0, 0x779ea450, 0x1053a120, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/net.go:404 +0xb4
net.(*TCPConn).ReadFrom(0x1051c2b0, 0x779ea450, 0x1053a120, 0x779ea480, 0x1051c2b0, 0x0, 0x0)
	/opt/mipsgo/src/net/tcpsock_posix.go:72 +0x118
io.Copy(0x779ea438, 0x1051c2b0, 0x779ea450, 0x1053a120, 0x0, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:358 +0x154
main.func·001()
	/home/openwrt/kcptun/client/main.go:64 +0xd8
created by main.handleClient
	/home/openwrt/kcptun/client/main.go:64 +0x448

goroutine 20 [IO wait]:
net.(*pollDesc).Wait(0x10560678, 0x72, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:84 +0x4c
net.(*pollDesc).WaitRead(0x10560678, 0x0, 0x0)
	/opt/mipsgo/src/net/fd_poll_runtime.go:89 +0x48
net.(*netFD).Read(0x10560640, 0x1064c000, 0x8000, 0x8000, 0x0, 0x779e8b10, 0x10538350)
	/opt/mipsgo/src/net/fd_unix.go:242 +0x3e0
net.(*conn).Read(0x1051c2b0, 0x1064c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/opt/mipsgo/src/net/net.go:121 +0xf0
io.Copy(0x779ea4c8, 0x1053a120, 0x779ea4e0, 0x1051c2b0, 0x0, 0x3, 0x0, 0x0)
	/opt/mipsgo/src/io/io.go:362 +0x208
main.func·002()
	/home/openwrt/kcptun/client/main.go:67 +0xd8
created by main.handleClient
	/home/openwrt/kcptun/client/main.go:67 +0x578
`

**Comment by allenkey666** [comment]
use --nocomp or "nocomp": true

**Comment by tisswb** [comment]
@bettermanbao 谢谢，我回家试试
