### ISSUE TITLE
有关于DNS解析的一个问题

### ISSUE THREAD

**Issue by christaikobo** [bettermanbao/openwrt-kcptun#19]
之前在某个ISSUE里面看到作者你提到，用PDNSD进行TCP的DNS解析
我试了一下，目前是DNSMASQ-CHINADNS-PDNSD(TCP_ONLY)，上游服务器是8.8.8.8，可以正常使用

就是想请教一下，PDNSD进行的解析，是否通过SS？是否通过KCPTUN？
有什么办法可以验证吗？

**Comment by allenkey666** [comment]
取决于你的iptables的设置，8.8.8.8的流量是否会被重定向到ss-redir。

**Comment by terrytw** [comment]
那请问一下

iptables -t nat -A PREROUTING -d 8.8.8.8 -j REDIRECT --to-port 1080

这样可以吗？（1080是SS-REDIR的端口）

**Comment by christaikobo** [comment]
请问一下这样写可以吗？

iptables -t nat -A PREROUTING -d 8.8.8.8 -j REDIRECT --to-port 1080

还是说应该写成

iptables -t nat -A PREROUTING -d 8.8.8.8 -j DNAT --to-destination 127.0.0.1:1080

然后有没有办法可以验证是否成功的通过KCPTUN转发了呢？

更新：
最终明白必须要指定协议类型
iptables -t nat -I PREROUTING -d 8.8.8.8 -p tcp -j REDIRECT --to-ports 1080
然后用一个极蠢的方法验证了

感谢你的指点！
