### ISSUE TITLE
请问703n等ar71路由器执行效率如何

### ISSUE THREAD

**Issue by livehl** [bettermanbao/openwrt-kcptun#24]
rt。同时运行ss的情况下，能否优化满带宽？

**Comment by allenkey666** [comment]
openwrt-kcptun需要64M内存才能运行，703n只有32M，所以没法运行。如果要强行运行，你可以试试看extroot后添加swap分区。
性能的话703n的ar9331 CPU稍微弱了一点，kcptun+ss，还要负责本无线的加密解密，估计4Mbps左右就是极限了。ar9341稍微好点，6Mbps应该能跑到。

**Comment by livehl** [comment]
谢谢
