### ISSUE TITLE
请编译一个ar71使用的20170120kcptun二进制文件

### ISSUE THREAD

**Issue by 1001knight** [bettermanbao/openwrt-kcptun#25]
你好，一直在等你更新20170120kcptun二进制文件。能尽快编译一个吗？

**Comment by allenkey666** [comment]
呵呵，周一更新吧。我以为都没人用了。

**Comment by 1001knight** [comment]
谢谢你的付出

2017-02-04 22:45 GMT+08:00, bettermanbao <notifications@github.com>:

**Comment by allenkey666** [comment]
已更
