### ISSUE TITLE
AR71xx Compression with Snappy (The first compression enabled release)版本 提速没有效果

### ISSUE THREAD

**Issue by pop4ever** [bettermanbao/openwrt-kcptun#7]
确认正常安装了，server和openwrt的client日志都正常。
但是提速没效果，这是为啥？

**Comment by blizzardster** [comment]
openwrt系统安装有问题
root@OpenWrt:~# ls
client_openwrt start.sh
root@OpenWrt:~# sh.start.sh
-ash: sh.start.sh: not found
root@OpenWrt:~# ./client_openwrt -r “111.111.111.111:29900” -l “:8380” -mtu 1400
-sndwnd 256 -rcvwnd 2048 -mode fast2 -dscp 46
-ash: ./client_openwrt: Permission denied
出现错误，不知道怎么办

**Comment by Anyfc** [comment]
@blizzardster Permission denied 无权限
