### ISSUE TITLE
大神可否把kcp-server也编译一份MIPS可用的啊，比如newifi mini或者d1什么的

### ISSUE THREAD

**Issue by yyysuo** [bettermanbao/openwrt-kcptun#9]
有了这个就可以不用SS，直接用KCPTUN了，非常感谢！
https://github.com/clangcn/kcp-server/tree/master/latest

**Comment by koolwiki** [comment]
支持

**Comment by allenkey666** [comment]
你把路由器放到国外用？

**Comment by koolwiki** [comment]
应该是指编译客户端，项目地址在这：
https://github.com/loveuall/kcptun

**Comment by yyysuo** [comment]
kcp-server来源于kcptun,但是服务器端和客户端跟kcptun不一样，我想在路由器上直接用kcp-server的客户端，但是kcp-server的客户端没有支持Mips的
地址：
https://github.com/clangcn/kcp-server/tree/master/20160811

**Comment by Kevin-KD** [comment]
kcptun本身就有server和client吧，请问能不能把server也编译一下，谢谢！

**Comment by allenkey666** [comment]
可以

**Comment by allenkey666** [comment]
已编

**Comment by yyysuo** [comment]
大神发布到哪里了啊，找不到呢？

**Comment by allenkey666** [comment]
https://github.com/bettermanbao/openwrt-kcptun/releases/tag/v20161111

**Comment by ninggu2008** [comment]
@yyysuo 为啥有了Kcptun就不需要ss了？kcptun不是给ss加速用的吗？我也很烦，服务器和pc、路由上都开着两个，ss和kcptun。
